Update group-pictures.md
next-theme/theme-next-docs pull request #96
Opened 2023-04-19 09:34 UTC by wxsms

https://github.com/next-theme/hexo-theme-next/issues/639

2023-04-19 13:45 UTC, njzjz requested changes

2023-04-19 13:45 UTC, njzjz commented on source/docs/tag-plugins/group-pictures.md
> +Please use absolute pathes for `<img>` inside group picture. See [this issue](https://github.com/next-theme/hexo-theme-next/issues/639#issuecomment-1514390433) for details.
pathes -> paths
picture-> pictures

2023-04-20 01:46 UTC, wxsms commented on source/docs/tag-plugins/group-pictures.md
> +Please use absolute pathes for `<img>` inside group picture. See [this issue](https://github.com/next-theme/hexo-theme-next/issues/639#issuecomment-1514390433) for details.
```suggestion
Please use absolute paths for `<img>` inside group pictures. See [this issue](https://github.com/next-theme/hexo-theme-next/issues/639#issuecomment-1514390433) for details.
```

2023-04-20 21:54 UTC, njzjz approved these changes

2023-04-21 03:45 UTC, merged